site_name: AD Test
site_description: This site covers AD Test information
repo_url: https://github.com/bharnden/adtest
theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: teal
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: teal
      accent: teal    
  features:
    - navigation.path
    - navigation.instant
markdown_extensions:
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
nav:
  - Home: index.md
  - Page1: page1.md
  - Page2: page2.md